package com.ray.LintCode;

import com.ray.io.Out;

/**
 * Description :
 *   Given two strings **s** and **t** which consist of only lowercase letters.
 *   
 *   String **t** is generated by random shuffling string **s** and then add one more letter at a random position.
 *   
 *   Find the letter that was added in **t**.
 *
 * Example :
 *   **Example：**
 *   ```
 *   Input：s = "abcd"，t = "abcde"
 *   Output：'e'
 *   Explanation：'e' is the letter that was added.
 *   ```
 *
 * Challenge :
 *   
 *
 * @author rays1
 * @url    https://www.lintcode.cn/problem/find-the-difference/description
 * @date   2019-07-03 17:42:28
 */
public class L_1266_Find_the_Difference {

    static class Solution {
    
        
    
    }
    
    public static void main(String[] args) {
        
        Out.p(new Solution());
        
    }

}
