package com.ray.leetcode.resolved;

import com.ray.io.Out;

/**
 * Find the Difference
 * -----------------------------------------------------------------------------
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Example:
 *      Example 1
 *      Input:
 *      s = "abcd"
 *      t = "abcde"
 *      Output:
 *      e
 *      Explanation:
 *      'e' is the letter that was added.
 *
 * Level : Easy
 *
 * @author  ray
 * @link    https://leetcode-cn.com/problems/find-the-difference/
 * @since   2020-03-23 21:50:17
 */
public class L0389_Find_the_Difference {
    /**
     * 类似重复元素找单个
     */
    static class Solution {
        public char findTheDifference(String s, String t) {
            int c = 0;
            for (int i = 0; i < s.length(); i++)
                c ^= s.charAt(i);
            for (int i = 0; i < t.length(); i++)
                c ^= t.charAt(i);
            return (char)c;
        }
    }
    
    public static void main(String[] args) {
        Out.p(new Solution());
    }
}
